#!/usr/bin/env python3
"""
Export the raw telemetry generated by one red-team session so it can be
replayed later (via replay_session.py) for defender testing without paying
for another live attacker run.

    python3 pipeline/redteam/export_session.py --session 7
    python3 pipeline/redteam/export_session.py --session 7 --out-dir attacker/loot/replays/session-7

Pulls every `events` row whose src_ip matches one of the IPs this session
ever attacked from (attacker_ip plus session_ip_history, since rotate_ip()
means a session can span more than one address) and whose ts falls inside
[started, ended] (open-ended if the session never finished). Writes one
NDJSON file per source containing exactly the `raw` column -- the same
bytes ingest.py originally tailed -- so replay_session.py can feed them
back through ingest.ingest_line() unchanged, plus a manifest.json with the
session's metadata and a best-effort scan for root-shell evidence in its
loot/pending_actions output.

Root-shell detection is deliberately NOT a model judgment call (nothing here
calls an LLM) -- it's a plain regex scan over tool output, same spirit as
agent.py's own FLAG_RE capture. It's a hint for a human to confirm, not a
verdict: absence of a match doesn't mean the session failed, and a match
doesn't guarantee a stable shell either.
"""

import argparse
import json
import os
import re
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PIPELINE = os.path.dirname(HERE)
ROOT = os.path.dirname(PIPELINE)
sys.path.insert(0, PIPELINE)

DB_PATH = os.path.join(ROOT, "soc.db")
DEFAULT_OUT_ROOT = os.path.join(ROOT, "attacker", "loot", "replays")

SOURCES = ("cowrie", "nginx", "suricata", "wazuh")

ROOT_EVIDENCE_PATTERNS = [
    re.compile(r"uid=0\(root\)", re.IGNORECASE),
    re.compile(r"\bwhoami\b[^\n]*\n\s*root\b", re.IGNORECASE),
    re.compile(r"meterpreter session \d+ opened", re.IGNORECASE),
    re.compile(r"nt authority\\system", re.IGNORECASE),
    re.compile(r"\broot@[\w.-]+[:#]", re.IGNORECASE),
    re.compile(r"\bEUID=0\b"),
]


def connect(db_path=None):
    conn = sqlite3.connect(db_path or DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def session_ips(conn, session_id):
    row = conn.execute(
        "SELECT attacker_ip FROM redteam_sessions WHERE id=?", (session_id,)
    ).fetchone()
    if row is None:
        return None
    ips = set()
    if row["attacker_ip"]:
        ips.add(row["attacker_ip"])
    for r in conn.execute(
        "SELECT old_ip, new_ip FROM session_ip_history WHERE session_id=?", (session_id,)
    ):
        if r["old_ip"]:
            ips.add(r["old_ip"])
        if r["new_ip"]:
            ips.add(r["new_ip"])
    return ips


def scan_root_evidence(conn, session_id):
    """Best-effort regex scan over this session's loot summaries and
    executed pending_actions results. Returns a list of {source, id, tool,
    target, pattern, snippet} hits -- evidence for a human to check, not an
    automatic pass/fail."""
    hits = []

    for r in conn.execute(
        "SELECT id, tool, target, summary FROM loot WHERE session_id=?", (session_id,)
    ):
        text = r["summary"] or ""
        for pat in ROOT_EVIDENCE_PATTERNS:
            m = pat.search(text)
            if m:
                start = max(0, m.start() - 40)
                hits.append({
                    "source": "loot", "id": r["id"], "tool": r["tool"], "target": r["target"],
                    "pattern": pat.pattern, "snippet": text[start:m.end() + 40].strip(),
                })

    for r in conn.execute(
        "SELECT id, tool, target, result_json FROM pending_actions "
        "WHERE session_id=? AND executed=1", (session_id,)
    ):
        text = r["result_json"] or ""
        for pat in ROOT_EVIDENCE_PATTERNS:
            m = pat.search(text)
            if m:
                start = max(0, m.start() - 40)
                hits.append({
                    "source": "pending_actions", "id": r["id"], "tool": r["tool"], "target": r["target"],
                    "pattern": pat.pattern, "snippet": text[start:m.end() + 40].strip(),
                })

    return hits


def export_events(conn, ips, started, ended, out_dir):
    counts = {}
    for source in SOURCES:
        sql = (
            "SELECT raw FROM events WHERE source=? AND ts>=? "
            + ("AND ts<=? " if ended else "")
            + "AND src_ip IN (%s) ORDER BY ts ASC" % ",".join("?" * len(ips))
        )
        params = [source, started] + ([ended] if ended else []) + list(ips)
        rows = conn.execute(sql, params).fetchall()
        counts[source] = len(rows)
        if not rows:
            continue
        path = os.path.join(out_dir, f"{source}.ndjson")
        with open(path, "w") as f:
            for r in rows:
                f.write(r["raw"].rstrip("\n") + "\n")
    return counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--session", type=int, required=True, metavar="ID")
    ap.add_argument("--out-dir", default=None,
                     help="default: attacker/loot/replays/session-<ID>/")
    ap.add_argument("--db-path", default=None, help="default: soc.db")
    args = ap.parse_args()

    conn = connect(args.db_path)

    session = conn.execute(
        "SELECT * FROM redteam_sessions WHERE id=?", (args.session,)
    ).fetchone()
    if session is None:
        print(f"[!] no redteam_sessions row with id={args.session}")
        return 1

    ips = session_ips(conn, args.session)
    if not ips:
        print(f"[!] session {args.session} has no recorded attacker_ip -- nothing to export")
        return 1

    out_dir = args.out_dir or os.path.join(DEFAULT_OUT_ROOT, f"session-{args.session}")
    os.makedirs(out_dir, exist_ok=True)

    counts = export_events(conn, ips, session["started"], session["ended"], out_dir)
    total = sum(counts.values())

    evidence = scan_root_evidence(conn, args.session)

    manifest = {
        "session_id": args.session,
        "provider": session["provider"],
        "model": session["model"],
        "status": session["status"],
        "stage": session["stage"],
        "started": session["started"],
        "ended": session["ended"],
        "attacker_ips": sorted(ips),
        "event_counts": counts,
        "root_shell_evidence": evidence,
    }
    with open(os.path.join(out_dir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"[*] session {args.session}: status={session['status']} stage={session['stage']} "
          f"ips={sorted(ips)}")
    print(f"[*] exported {total} event(s) across {sum(1 for n in counts.values() if n)} source(s) "
          f"-> {out_dir}")
    for source, n in counts.items():
        if n:
            print(f"    {source:<8} {n}")

    if evidence:
        print(f"\n[*] {len(evidence)} possible root-shell indicator(s) found -- CONFIRM MANUALLY:")
        for h in evidence:
            print(f"    [{h['source']}#{h['id']}] tool={h['tool']} target={h['target']}: "
                  f"...{h['snippet']}...")
    else:
        print("\n[!] no root-shell indicators found in loot/pending_actions output for this "
              "session -- check manually before treating this as a successful replay case.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
